-- GENERATED by tools/gen-supabase.mjs — do not edit. Permission seed + project-scoped tables with RLS.

insert into role_caps (role, cap, side_only) values
  ('owner', 'project.view', null),
  ('owner', 'brief.view', null),
  ('owner', 'brief.edit', 'provider'),
  ('owner', 'brief.submit', 'client'),
  ('owner', 'scope.view', null),
  ('owner', 'scope.edit', 'provider'),
  ('owner', 'proposal.view', null),
  ('owner', 'proposal.edit', 'provider'),
  ('owner', 'proposal.respond', 'client'),
  ('owner', 'contract.view', null),
  ('owner', 'contract.edit', 'provider'),
  ('owner', 'contract.accept', 'client'),
  ('owner', 'files.view', null),
  ('owner', 'files.upload', null),
  ('owner', 'feedback.view', null),
  ('owner', 'feedback.write', null),
  ('owner', 'revisions.view', null),
  ('owner', 'revisions.manage', 'provider'),
  ('owner', 'revisions.request', 'client'),
  ('owner', 'approvals.view', null),
  ('owner', 'approvals.request', 'provider'),
  ('owner', 'approvals.respond', 'client'),
  ('owner', 'changes.respond', 'client'),
  ('owner', 'finance.view', null),
  ('owner', 'finance.manage', 'provider'),
  ('owner', 'finance.pay', 'client'),
  ('owner', 'delivery.manage', 'provider'),
  ('owner', 'team.view', null),
  ('owner', 'team.manage', null),
  ('owner', 'tasks.view', null),
  ('owner', 'tasks.manage', null),
  ('owner', 'messages', null),
  ('owner', 'calendar.view', null),
  ('owner', 'activity.view', null),
  ('owner', 'settings.manage', 'provider'),
  ('manager', 'project.view', null),
  ('manager', 'brief.view', null),
  ('manager', 'brief.edit', 'provider'),
  ('manager', 'brief.submit', 'client'),
  ('manager', 'scope.view', null),
  ('manager', 'scope.edit', 'provider'),
  ('manager', 'proposal.view', null),
  ('manager', 'proposal.edit', 'provider'),
  ('manager', 'proposal.respond', 'client'),
  ('manager', 'contract.view', null),
  ('manager', 'contract.edit', 'provider'),
  ('manager', 'contract.accept', 'client'),
  ('manager', 'files.view', null),
  ('manager', 'files.upload', null),
  ('manager', 'feedback.view', null),
  ('manager', 'feedback.write', null),
  ('manager', 'revisions.view', null),
  ('manager', 'revisions.manage', 'provider'),
  ('manager', 'revisions.request', 'client'),
  ('manager', 'approvals.view', null),
  ('manager', 'approvals.request', 'provider'),
  ('manager', 'approvals.respond', 'client'),
  ('manager', 'changes.respond', 'client'),
  ('manager', 'finance.view', null),
  ('manager', 'finance.manage', 'provider'),
  ('manager', 'finance.pay', 'client'),
  ('manager', 'delivery.manage', 'provider'),
  ('manager', 'team.view', null),
  ('manager', 'team.manage', null),
  ('manager', 'tasks.view', null),
  ('manager', 'tasks.manage', null),
  ('manager', 'messages', null),
  ('manager', 'calendar.view', null),
  ('manager', 'activity.view', null),
  ('manager', 'settings.manage', 'provider'),
  ('producer', 'project.view', null),
  ('producer', 'brief.view', null),
  ('producer', 'brief.edit', 'provider'),
  ('producer', 'brief.submit', 'client'),
  ('producer', 'scope.view', null),
  ('producer', 'scope.edit', 'provider'),
  ('producer', 'proposal.view', null),
  ('producer', 'proposal.edit', 'provider'),
  ('producer', 'proposal.respond', 'client'),
  ('producer', 'contract.view', null),
  ('producer', 'contract.edit', 'provider'),
  ('producer', 'contract.accept', 'client'),
  ('producer', 'files.view', null),
  ('producer', 'files.upload', null),
  ('producer', 'feedback.view', null),
  ('producer', 'feedback.write', null),
  ('producer', 'revisions.view', null),
  ('producer', 'revisions.manage', 'provider'),
  ('producer', 'revisions.request', 'client'),
  ('producer', 'approvals.view', null),
  ('producer', 'approvals.request', 'provider'),
  ('producer', 'approvals.respond', 'client'),
  ('producer', 'changes.respond', 'client'),
  ('producer', 'finance.view', null),
  ('producer', 'delivery.manage', 'provider'),
  ('producer', 'team.view', null),
  ('producer', 'tasks.view', null),
  ('producer', 'tasks.manage', null),
  ('producer', 'messages', null),
  ('producer', 'calendar.view', null),
  ('producer', 'activity.view', null),
  ('director', 'project.view', null),
  ('director', 'brief.view', null),
  ('director', 'brief.edit', 'provider'),
  ('director', 'brief.submit', 'client'),
  ('director', 'scope.view', null),
  ('director', 'scope.edit', 'provider'),
  ('director', 'proposal.view', null),
  ('director', 'proposal.edit', 'provider'),
  ('director', 'proposal.respond', 'client'),
  ('director', 'contract.view', null),
  ('director', 'contract.edit', 'provider'),
  ('director', 'contract.accept', 'client'),
  ('director', 'files.view', null),
  ('director', 'files.upload', null),
  ('director', 'feedback.view', null),
  ('director', 'feedback.write', null),
  ('director', 'revisions.view', null),
  ('director', 'revisions.manage', 'provider'),
  ('director', 'revisions.request', 'client'),
  ('director', 'approvals.view', null),
  ('director', 'approvals.request', 'provider'),
  ('director', 'approvals.respond', 'client'),
  ('director', 'changes.respond', 'client'),
  ('director', 'finance.view', null),
  ('director', 'delivery.manage', 'provider'),
  ('director', 'team.view', null),
  ('director', 'team.manage', null),
  ('director', 'tasks.view', null),
  ('director', 'tasks.manage', null),
  ('director', 'messages', null),
  ('director', 'calendar.view', null),
  ('director', 'activity.view', null),
  ('designer', 'project.view', null),
  ('designer', 'brief.view', null),
  ('designer', 'scope.view', null),
  ('designer', 'files.view', null),
  ('designer', 'files.upload', null),
  ('designer', 'feedback.view', null),
  ('designer', 'feedback.write', null),
  ('designer', 'revisions.view', null),
  ('designer', 'tasks.view', null),
  ('designer', 'messages', null),
  ('designer', 'calendar.view', null),
  ('designer', 'activity.view', null),
  ('designer', 'team.view', null),
  ('designer', 'tasks.manage', null),
  ('editor', 'project.view', null),
  ('editor', 'brief.view', null),
  ('editor', 'scope.view', null),
  ('editor', 'files.view', null),
  ('editor', 'files.upload', null),
  ('editor', 'feedback.view', null),
  ('editor', 'feedback.write', null),
  ('editor', 'revisions.view', null),
  ('editor', 'tasks.view', null),
  ('editor', 'messages', null),
  ('editor', 'calendar.view', null),
  ('editor', 'activity.view', null),
  ('editor', 'team.view', null),
  ('editor', 'tasks.manage', null),
  ('reviewer', 'project.view', null),
  ('reviewer', 'brief.view', null),
  ('reviewer', 'scope.view', null),
  ('reviewer', 'files.view', null),
  ('reviewer', 'feedback.view', null),
  ('reviewer', 'feedback.write', null),
  ('reviewer', 'revisions.view', null),
  ('reviewer', 'revisions.request', 'client'),
  ('reviewer', 'brief.submit', 'client'),
  ('reviewer', 'approvals.view', null),
  ('reviewer', 'tasks.view', null),
  ('reviewer', 'messages', null),
  ('reviewer', 'calendar.view', null),
  ('reviewer', 'activity.view', null),
  ('reviewer', 'team.view', null),
  ('approver', 'project.view', null),
  ('approver', 'brief.view', null),
  ('approver', 'scope.view', null),
  ('approver', 'files.view', null),
  ('approver', 'feedback.view', null),
  ('approver', 'feedback.write', null),
  ('approver', 'revisions.view', null),
  ('approver', 'revisions.request', 'client'),
  ('approver', 'brief.submit', 'client'),
  ('approver', 'approvals.view', null),
  ('approver', 'tasks.view', null),
  ('approver', 'messages', null),
  ('approver', 'calendar.view', null),
  ('approver', 'activity.view', null),
  ('approver', 'team.view', null),
  ('approver', 'approvals.respond', 'client'),
  ('approver', 'proposal.view', null),
  ('approver', 'proposal.respond', 'client'),
  ('approver', 'contract.view', null),
  ('approver', 'contract.accept', 'client'),
  ('approver', 'changes.respond', 'client'),
  ('finance', 'project.view', null),
  ('finance', 'scope.view', null),
  ('finance', 'proposal.view', null),
  ('finance', 'contract.view', null),
  ('finance', 'approvals.view', null),
  ('finance', 'finance.view', null),
  ('finance', 'finance.manage', 'provider'),
  ('finance', 'finance.pay', 'client'),
  ('finance', 'messages', null),
  ('finance', 'calendar.view', null),
  ('finance', 'activity.view', null),
  ('finance', 'team.view', null),
  ('viewer', 'project.view', null),
  ('viewer', 'brief.view', null),
  ('viewer', 'scope.view', null),
  ('viewer', 'files.view', null),
  ('viewer', 'feedback.view', null),
  ('viewer', 'revisions.view', null),
  ('viewer', 'approvals.view', null),
  ('viewer', 'calendar.view', null),
  ('viewer', 'activity.view', null),
  ('viewer', 'team.view', null);

insert into implicit_roles (org_role, project_role) values
  ('owner', 'owner'),
  ('admin', 'owner'),
  ('manager', 'manager'),
  ('finance', 'finance');

insert into ws_caps (role, cap) values
  ('owner', '*'),
  ('admin', '*'),
  ('manager', 'projects.create'),
  ('manager', 'clients.view'),
  ('manager', 'clients.manage'),
  ('manager', 'finance.view'),
  ('manager', 'proposal.view'),
  ('manager', 'contract.view'),
  ('manager', 'portfolio'),
  ('manager', 'analytics'),
  ('manager', 'members.view'),
  ('finance', 'finance.view'),
  ('finance', 'finance.manage'),
  ('finance', 'proposal.view'),
  ('finance', 'contract.view'),
  ('finance', 'clients.view'),
  ('finance', 'members.view'),
  ('member', 'projects.create'),
  ('member', 'members.view'),
  ('viewer', 'members.view');

create table briefs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on briefs (project_id);
create trigger t_briefs before update on briefs for each row execute function touch_updated_at();
alter table briefs enable row level security;
create policy briefs_select on briefs for select to authenticated using (project_can(project_id, 'brief.view'));
create policy briefs_insert on briefs for insert to authenticated with check (exists (select 1 from unnest(array['brief.edit', 'brief.submit']) c where project_can(project_id, c)));
create policy briefs_update on briefs for update to authenticated using (exists (select 1 from unnest(array['brief.edit', 'brief.submit']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['brief.edit', 'brief.submit']) c where project_can(project_id, c)));
create policy briefs_delete on briefs for delete to authenticated using (exists (select 1 from unnest(array['brief.edit', 'brief.submit']) c where project_can(project_id, c)));

create table deliverables (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on deliverables (project_id);
create trigger t_deliverables before update on deliverables for each row execute function touch_updated_at();
alter table deliverables enable row level security;
create policy deliverables_select on deliverables for select to authenticated using (project_can(project_id, 'scope.view'));
create policy deliverables_insert on deliverables for insert to authenticated with check (exists (select 1 from unnest(array['scope.edit']) c where project_can(project_id, c)));
create policy deliverables_update on deliverables for update to authenticated using (exists (select 1 from unnest(array['scope.edit']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['scope.edit']) c where project_can(project_id, c)));
create policy deliverables_delete on deliverables for delete to authenticated using (exists (select 1 from unnest(array['scope.edit']) c where project_can(project_id, c)));

create table proposals (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on proposals (project_id);
create trigger t_proposals before update on proposals for each row execute function touch_updated_at();
alter table proposals enable row level security;
create policy proposals_select on proposals for select to authenticated using (project_can(project_id, 'proposal.view'));
create policy proposals_insert on proposals for insert to authenticated with check (exists (select 1 from unnest(array['proposal.edit', 'proposal.respond']) c where project_can(project_id, c)));
create policy proposals_update on proposals for update to authenticated using (exists (select 1 from unnest(array['proposal.edit', 'proposal.respond']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['proposal.edit', 'proposal.respond']) c where project_can(project_id, c)));
create policy proposals_delete on proposals for delete to authenticated using (exists (select 1 from unnest(array['proposal.edit', 'proposal.respond']) c where project_can(project_id, c)));

create table proposal_items (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on proposal_items (project_id);
create trigger t_proposal_items before update on proposal_items for each row execute function touch_updated_at();
alter table proposal_items enable row level security;
create policy proposal_items_select on proposal_items for select to authenticated using (project_can(project_id, 'proposal.view'));
create policy proposal_items_insert on proposal_items for insert to authenticated with check (exists (select 1 from unnest(array['proposal.edit']) c where project_can(project_id, c)));
create policy proposal_items_update on proposal_items for update to authenticated using (exists (select 1 from unnest(array['proposal.edit']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['proposal.edit']) c where project_can(project_id, c)));
create policy proposal_items_delete on proposal_items for delete to authenticated using (exists (select 1 from unnest(array['proposal.edit']) c where project_can(project_id, c)));

create table contracts (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on contracts (project_id);
create trigger t_contracts before update on contracts for each row execute function touch_updated_at();
alter table contracts enable row level security;
create policy contracts_select on contracts for select to authenticated using (project_can(project_id, 'contract.view'));
create policy contracts_insert on contracts for insert to authenticated with check (exists (select 1 from unnest(array['contract.edit', 'contract.accept']) c where project_can(project_id, c)));
create policy contracts_update on contracts for update to authenticated using (exists (select 1 from unnest(array['contract.edit', 'contract.accept']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['contract.edit', 'contract.accept']) c where project_can(project_id, c)));
create policy contracts_delete on contracts for delete to authenticated using (exists (select 1 from unnest(array['contract.edit', 'contract.accept']) c where project_can(project_id, c)));

create table change_orders (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on change_orders (project_id);
create trigger t_change_orders before update on change_orders for each row execute function touch_updated_at();
alter table change_orders enable row level security;
create policy change_orders_select on change_orders for select to authenticated using (project_can(project_id, 'scope.view'));
create policy change_orders_insert on change_orders for insert to authenticated with check (exists (select 1 from unnest(array['scope.edit', 'changes.respond']) c where project_can(project_id, c)));
create policy change_orders_update on change_orders for update to authenticated using (exists (select 1 from unnest(array['scope.edit', 'changes.respond']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['scope.edit', 'changes.respond']) c where project_can(project_id, c)));
create policy change_orders_delete on change_orders for delete to authenticated using (exists (select 1 from unnest(array['scope.edit', 'changes.respond']) c where project_can(project_id, c)));

create table files (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on files (project_id);
create trigger t_files before update on files for each row execute function touch_updated_at();
alter table files enable row level security;
create policy files_select on files for select to authenticated using (project_can(project_id, 'files.view'));
create policy files_insert on files for insert to authenticated with check (exists (select 1 from unnest(array['files.upload']) c where project_can(project_id, c)));
create policy files_update on files for update to authenticated using (exists (select 1 from unnest(array['files.upload']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['files.upload']) c where project_can(project_id, c)));
create policy files_delete on files for delete to authenticated using (exists (select 1 from unnest(array['files.upload']) c where project_can(project_id, c)));

create table file_versions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on file_versions (project_id);
create trigger t_file_versions before update on file_versions for each row execute function touch_updated_at();
alter table file_versions enable row level security;
create policy file_versions_select on file_versions for select to authenticated using (project_can(project_id, 'files.view'));
create policy file_versions_insert on file_versions for insert to authenticated with check (exists (select 1 from unnest(array['files.upload']) c where project_can(project_id, c)));
create policy file_versions_update on file_versions for update to authenticated using (exists (select 1 from unnest(array['files.upload']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['files.upload']) c where project_can(project_id, c)));
create policy file_versions_delete on file_versions for delete to authenticated using (exists (select 1 from unnest(array['files.upload']) c where project_can(project_id, c)));

create table feedback (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on feedback (project_id);
create trigger t_feedback before update on feedback for each row execute function touch_updated_at();
alter table feedback enable row level security;
create policy feedback_select on feedback for select to authenticated using (project_can(project_id, 'feedback.view'));
create policy feedback_insert on feedback for insert to authenticated with check (exists (select 1 from unnest(array['feedback.write']) c where project_can(project_id, c)));
create policy feedback_update on feedback for update to authenticated using (exists (select 1 from unnest(array['feedback.write']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['feedback.write']) c where project_can(project_id, c)));
create policy feedback_delete on feedback for delete to authenticated using (exists (select 1 from unnest(array['feedback.write']) c where project_can(project_id, c)));

create table revision_rounds (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on revision_rounds (project_id);
create trigger t_revision_rounds before update on revision_rounds for each row execute function touch_updated_at();
alter table revision_rounds enable row level security;
create policy revision_rounds_select on revision_rounds for select to authenticated using (project_can(project_id, 'revisions.view'));
create policy revision_rounds_insert on revision_rounds for insert to authenticated with check (exists (select 1 from unnest(array['revisions.manage', 'revisions.request']) c where project_can(project_id, c)));
create policy revision_rounds_update on revision_rounds for update to authenticated using (exists (select 1 from unnest(array['revisions.manage', 'revisions.request']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['revisions.manage', 'revisions.request']) c where project_can(project_id, c)));
create policy revision_rounds_delete on revision_rounds for delete to authenticated using (exists (select 1 from unnest(array['revisions.manage', 'revisions.request']) c where project_can(project_id, c)));

create table approvals (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on approvals (project_id);
create trigger t_approvals before update on approvals for each row execute function touch_updated_at();
alter table approvals enable row level security;
create policy approvals_select on approvals for select to authenticated using (project_can(project_id, 'approvals.view'));
create policy approvals_insert on approvals for insert to authenticated with check (exists (select 1 from unnest(array['approvals.request', 'approvals.respond']) c where project_can(project_id, c)));
create policy approvals_update on approvals for update to authenticated using (exists (select 1 from unnest(array['approvals.request', 'approvals.respond']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['approvals.request', 'approvals.respond']) c where project_can(project_id, c)));
create policy approvals_delete on approvals for delete to authenticated using (exists (select 1 from unnest(array['approvals.request', 'approvals.respond']) c where project_can(project_id, c)));

create table invoices (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on invoices (project_id);
create trigger t_invoices before update on invoices for each row execute function touch_updated_at();
alter table invoices enable row level security;
create policy invoices_select on invoices for select to authenticated using (project_can(project_id, 'finance.view'));
create policy invoices_insert on invoices for insert to authenticated with check (exists (select 1 from unnest(array['finance.manage', 'finance.pay']) c where project_can(project_id, c)));
create policy invoices_update on invoices for update to authenticated using (exists (select 1 from unnest(array['finance.manage', 'finance.pay']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['finance.manage', 'finance.pay']) c where project_can(project_id, c)));
create policy invoices_delete on invoices for delete to authenticated using (exists (select 1 from unnest(array['finance.manage', 'finance.pay']) c where project_can(project_id, c)));

create table invoice_items (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on invoice_items (project_id);
create trigger t_invoice_items before update on invoice_items for each row execute function touch_updated_at();
alter table invoice_items enable row level security;
create policy invoice_items_select on invoice_items for select to authenticated using (project_can(project_id, 'finance.view'));
create policy invoice_items_insert on invoice_items for insert to authenticated with check (exists (select 1 from unnest(array['finance.manage']) c where project_can(project_id, c)));
create policy invoice_items_update on invoice_items for update to authenticated using (exists (select 1 from unnest(array['finance.manage']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['finance.manage']) c where project_can(project_id, c)));
create policy invoice_items_delete on invoice_items for delete to authenticated using (exists (select 1 from unnest(array['finance.manage']) c where project_can(project_id, c)));

create table payments (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on payments (project_id);
create trigger t_payments before update on payments for each row execute function touch_updated_at();
alter table payments enable row level security;
create policy payments_select on payments for select to authenticated using (project_can(project_id, 'finance.view'));
create policy payments_insert on payments for insert to authenticated with check (exists (select 1 from unnest(array['finance.manage', 'finance.pay']) c where project_can(project_id, c)));
create policy payments_update on payments for update to authenticated using (exists (select 1 from unnest(array['finance.manage', 'finance.pay']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['finance.manage', 'finance.pay']) c where project_can(project_id, c)));
create policy payments_delete on payments for delete to authenticated using (exists (select 1 from unnest(array['finance.manage', 'finance.pay']) c where project_can(project_id, c)));

create table tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on tasks (project_id);
create trigger t_tasks before update on tasks for each row execute function touch_updated_at();
alter table tasks enable row level security;
create policy tasks_select on tasks for select to authenticated using (project_can(project_id, 'tasks.view'));
create policy tasks_insert on tasks for insert to authenticated with check (exists (select 1 from unnest(array['tasks.manage']) c where project_can(project_id, c)));
create policy tasks_update on tasks for update to authenticated using (exists (select 1 from unnest(array['tasks.manage']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['tasks.manage']) c where project_can(project_id, c)));
create policy tasks_delete on tasks for delete to authenticated using (exists (select 1 from unnest(array['tasks.manage']) c where project_can(project_id, c)));

create table messages (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on messages (project_id);
create trigger t_messages before update on messages for each row execute function touch_updated_at();
alter table messages enable row level security;
create policy messages_select on messages for select to authenticated using (project_can(project_id, 'messages'));
create policy messages_insert on messages for insert to authenticated with check (exists (select 1 from unnest(array['messages']) c where project_can(project_id, c)));
create policy messages_update on messages for update to authenticated using (exists (select 1 from unnest(array['messages']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['messages']) c where project_can(project_id, c)));
create policy messages_delete on messages for delete to authenticated using (exists (select 1 from unnest(array['messages']) c where project_can(project_id, c)));

create table events (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  data jsonb not null default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index on events (project_id);
create trigger t_events before update on events for each row execute function touch_updated_at();
alter table events enable row level security;
create policy events_select on events for select to authenticated using (project_can(project_id, 'calendar.view'));
create policy events_insert on events for insert to authenticated with check (exists (select 1 from unnest(array['calendar.view']) c where project_can(project_id, c)));
create policy events_update on events for update to authenticated using (exists (select 1 from unnest(array['calendar.view']) c where project_can(project_id, c)))
  with check (exists (select 1 from unnest(array['calendar.view']) c where project_can(project_id, c)));
create policy events_delete on events for delete to authenticated using (exists (select 1 from unnest(array['calendar.view']) c where project_can(project_id, c)));

-- Activity log: append-only (no update/delete policy), finance actions hidden without finance.view.
create table activity_logs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references projects(id) on delete cascade,
  actor_user_id uuid default auth.uid(), action text not null,
  data jsonb not null default '{}', created_at timestamptz not null default now()
);
create index on activity_logs (project_id, created_at desc);
alter table activity_logs enable row level security;
create policy activity_select on activity_logs for select to authenticated using (
  project_can(project_id, 'activity.view') and (project_can(project_id, 'finance.view') or action !~ '^(invoice|payment|deposit)\.'));
create policy activity_insert on activity_logs for insert to authenticated with check (project_can(project_id, 'project.view'));

-- Notifications belong to one person.
create table notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references projects(id) on delete cascade,
  type text not null check (type in ('message','activity','reminder','action')),
  data jsonb not null default '{}', read_at timestamptz, created_at timestamptz not null default now()
);
create index on notifications (user_id, created_at desc);
alter table notifications enable row level security;
create policy notif_select on notifications for select to authenticated using (user_id = auth.uid());
create policy notif_update on notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy notif_delete on notifications for delete to authenticated using (user_id = auth.uid());
create policy notif_insert on notifications for insert to authenticated with check (project_id is null or project_can(project_id, 'project.view'));

-- Portfolio belongs to a workspace.
create table portfolio_items (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  data jsonb not null default '{}',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table portfolio_items enable row level security;
create policy portfolio_all on portfolio_items for all to authenticated using (ws_can(workspace_id, 'portfolio')) with check (ws_can(workspace_id, 'portfolio'));
